### ISSUE TITLE
Brush tool usability issues

### ISSUE THREAD

**Issue by kryptot7** [zrispo/wick#620]
I really like Wick so far, it shows a lot of potential 😄 As an artist, I encountered these issues:
- [x] The brush tool "smooths" small strokes out of existence. Drawing dots (i.e. for eyes) usually requires multiple tries as they repeatedly get "smoothed" into nothing. Setting brush size to the minimum usually produces no lines due to this bug. VIDEO of bug: [click](https://youtu.be/WgG_79hL8A8) (Edit: fixed link)
- [ ] Smaller brushes than 3 and lower smoothing ranges would be appreciated for detail work. 🖌 
- [ ] It doesn't seem to support Wacom tablets in Windows Ink mode. I use an old Wacom tablet (CTL-460) for drawing and had to disable Windows Ink in Wacom Preferences, or else the Brush tool would only draw one stroke and then not work again. A troubleshooting notice about this would be very helpful.
- [ ] It also lacks pressure sensitivity, but I understand that could be a lot of work 😅 The Pressure.js library looks promising in implementing basic functionality.
SYSTEM:
Windows 10 1703, Chrome 59, Intel i3-7100U

**Comment by zrispo** [comment]
Hi there! Thanks a lot for all the feedback!

 - Smoothing small strokes has been a problem for a while, I remember Flash having this same problem and it was notoriously annoying... Wick uses the same algorithm so I gotta find a way around this. For now, I just restricted the brush smoothing option to a smaller range:

https://github.com/zrispo/wick/blob/92d48b805c323a857d318196c26d25cec48bd1c2/src/editor/Interfaces.Toolbar.js#L99

 - I also allowed brush thickness to get a little smaller (now the range is 2-100) but at a thickness of 1, you start running into the same problem of paths disappearing even when smoothing is 100 ¯\_(ツ)_/¯

https://github.com/zrispo/wick/blob/92d48b805c323a857d318196c26d25cec48bd1c2/src/editor/Interfaces.Toolbar.js#L90

 - As for tablet support, it's something I've played around with using my own tablet (an Intuos 3) and I actually got pressure sensitivity to work at one point. However, it's been difficult to test different tablets because I only have one :( 

 - I actually have no idea why the brush is offset like it is in your video - does it only do that when you're using a tablet?

**Comment by kryptot7** [comment]
Okay, the brushes work much better now. 😄 Setting the smoothness to 100 actually makes the lines more pen-like instead of brush-like. They deviate less from the way they were drawn. So instead of being called smoothness, maybe it should be "Brush Hardness". The lines are pretty smooth either way.
Also, to get lower, more "brush"-y smoothing levels to work, try adjusting "wick/lib/potrace.js" turdsize variable depending on the brush radius. It's responsible for removing tiny speckles of paint.
Or, you could scale down the drawn brush-image by a factor of the brush radius, THEN potrace it, then scale it back up. This will make all lines look the same no matter what radius they are drawn at.

**Comment by zrispo** [comment]
Hmm yeah I'll try some experiments with potrace.js and see what I can do

Also feel free to play with the settings if you want - I'm not too picky about code contributions so if you find something that works better I can definitely add it to the codebase 😃
