### ISSUE TITLE
Scrubbing instant preview issues

### ISSUE THREAD

**Issue by kryptot7** [zrispo/wick#666]
(Mentioned in #663)
[When you hold down the mouse to start scrubbing, paths made with the Pen tool disappear until the mouse is released. Also, the instant preview skips some frames. If you scrub from frame 1 to frame 3, for example, it will skip frame 2.](https://youtu.be/oZt2z7Wha0U)

**Comment by zrispo** [comment]
Pushed a quick fix for this, should be working now

**Comment by kryptot7** [comment]
The frame skipping is fixed :)
However, the path issue is still present. Interestingly, I tried editing a brush stroke with the Pen tool, and when I grabbed the playhead to scrub the timeline, the stage showed the old version of the stroke from before I tweaked it. 😮 When I stopped scrubbing, the current version re-appeared and so did the Pen tool shapes.
I just noticed that frame thumbnails always display this way - my Pen tool paths are invisible, and the old version of the Pen-edited Brush stroke appears where the current version should be.

**Comment by zrispo** [comment]
Oh nice! I actually figured out the why the bug was happening from reading your comment, this has been an issue for a while...

To speed things up, Wick uses a faster renderer while doing things like scrubbing/preview playing/thumbnail rendering. The problem was the fast renderer wasn't being updated when paths changed, so it's a simple fix, but a hard to find problem~

I just pushed the fix, lemme know if it's working...

**Comment by kryptot7** [comment]
Woo hoo, it works! ^.^
It doesn't autopreview motion tweens, though.
Also, a couple of minor cosmetic changes. Now, that weird gradient open Pen path is the way it NORMALLY looks, which is weird but actually looks cool xD
![fea7ce54-1d32-4e1a-af51-cc1906260f30](https://user-images.githubusercontent.com/30781325/30517319-9020b9d8-9b29-11e7-8208-e7da3fa7b81f.gif)

**Comment by zrispo** [comment]
Whoops, nice catch with the motions tweens. Just fixed that.

**Comment by kryptot7** [comment]
Works great!
