### ISSUE TITLE
I'll look stupid, but I have to reccomend to make an offline editor too.

### ISSUE THREAD

**Issue by canary-animations** [zrispo/wick#676]
making the program to work only on a web browser is quite confusing to me, and it feels a bit odd and unstable. I would really like an offline editor, in the future. Also I wish if there could be the program's own file extension. I know both is very hard to make on Javascript, but I would really consider to use wick as my animating program if these two things are done.  Thanks and have a perfect day :)

**Comment by Luxapodular** [comment]
Hey Canary-Animations, we hear you! We actually started developing an offline version of the editor. Hopefully we'll be able to work out the bugs for that soon, but no promises on a release date yet. :)

We also looked into creating a wick-specific file extension but found a few issues (such as a computer not knowing what to do with it). @zrispo and I think this would be great, we just want to make sure we do it right! 

Also, we just made a forum earlier this week. We'd love if you signed up and added topics like this to the forum so we can start having more important discussions about Wick!

**Comment by Luxapodular** [comment]
@canary-animations Also, I'd love to see some of the stuff you've made so far!

**Comment by zrispo** [comment]
An offline downloadable version of Wick is in the works - there's some tricky stuff we still need to figure out still, for example I don't know how to make it so the desktop version will update itself so that it has the same functionality as the browser editor. Will hopefully figure that out soon!

About the file extensions - I'm doing some research today on how we could get browsers to recognize a `.wick` file or something custom like that. However, I've been thinking a lot about having all Wick projects be `.html` files, so that you could just double click them to see what they are, and uploading your project to the web would be very easy. Any thoughts?

**Comment by canary-animations** [comment]
Oh, ok. Thanks!
